version: "3"
services:
  load-balancer:
    ports:
      - "80:80"
  car-rental:
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: node index.js

