version: "3"
services:
  load-balancer:
    ports:
      - "5000:80"
  car-rental:
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev