version: "3"
services:
  load-balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - car-rental
  car-rental:
    build: .
    environment:
      - PORT=5050
    depends_on:
      - database
      - redis
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emash90
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb:/data/db
  redis:
    image: redis



volumes:
  mongodb: